# Generated by Django 5.2.8 on 2025-12-13 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('farmcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmcare.report'),
        ),
    ]
