# Generated by Django 5.2.8 on 2025-12-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available',
            field=models.BooleanField(default=True, help_text='Is the expert currently available?'),
        ),
        migrations.AddField(
            model_name='user',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='user',
            name='credentials',
            field=models.TextField(blank=True, help_text='Qualifications and credentials', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='specialties',
            field=models.CharField(blank=True, help_text='Comma separated list of specialties', max_length=250, null=True),
        ),
    ]
