# Generated by Django 5.2.8 on 2025-12-11 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmcare', '0002_report_assigned_to_report_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='report',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Payment Pending'), ('paid', 'Paid'), ('failed', 'Payment Failed')], default='unpaid', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa')], default='mpesa', max_length=20)),
                ('transaction_status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, max_length=200, null=True)),
                ('mpesa_merchant_request_id', models.CharField(blank=True, max_length=200, null=True)),
                ('mpesa_result_code', models.CharField(blank=True, max_length=10, null=True)),
                ('mpesa_result_description', models.TextField(blank=True, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='farmcare.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
